development:
  adapter: mysql2
  encoding: utf8
  database: simple_omniauth_server_development
  username: root
  password: root

test:
  adapter: mysql2
  encoding: utf8
  database: simple_omniauth_server_test
  username: root
  password: root


production:
  adapter: mysql2
  encoding: utf8
  database: simple_omniauth_server_production
  username: root
  password: root  